# Generated by Django 3.2.4 on 2023-07-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_ipmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='ipmodel',
            name='user',
            field=models.TextField(default=None),
        ),
    ]
