# Generated by Django 3.2.4 on 2023-07-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20230727_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.ManyToManyField(null=True, related_name='korishlars_soni', to='front.IpModel'),
        ),
        migrations.AddField(
            model_name='ipmodel',
            name='ip',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
