# Generated by Django 3.2.4 on 2023-07-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20230729_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='korishlars_soni', to='front.IpModel'),
        ),
    ]
