# Generated by Django 3.2.4 on 2023-07-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_alter_book_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nomi')),
                ('subject', models.TextField()),
                ('number', models.PositiveIntegerField()),
                ('tg_name', models.CharField(max_length=200, verbose_name='telegram nomi')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
